# Generated by Django 3.0.4 on 2020-03-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0002_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='categories',
            field=models.ManyToManyField(null=True, to='charityapp.Category'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(null=True, to='charityapp.Category'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(3, 'Zbiórka lokalna'), (2, 'Organizacja pozarządowa'), (1, 'Fundacja')], default=1),
        ),
    ]
