# Generated by Django 3.0.4 on 2020-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0003_auto_20200324_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='categories',
            field=models.ManyToManyField(to='charityapp.Category'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='charityapp.Category'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(1, 'Fundacja'), (3, 'Zbiórka lokalna'), (2, 'Organizacja pozarządowa')], default=1),
        ),
    ]
